### ISSUE TITLE
Incompatible with sgui 0.5.0 and mods that provide that version of sgui

### ISSUE THREAD

**Issue by JoeJoeTV** [Patbox/ArmorStandEditor#1]
When installed together with Version 0.5.0 or any Mod that provides that version of [sgui](https://github.com/Patbox/sgui) like [Easy Painter](https://modrinth.com/mod/easy_painter), the Server crashes as soon as the Armor Stand Editor Item(Flint) is right clicked to open the gui.

The crash report can be found here: https://paste.ubuntu.com/p/JZCmXnyzFJ/

Specs:
- Minecraft 1.16.5
- Java 16
- Fabric Loader 0.11.6
- Armor Stand Editor 1.2.0

This may have something to do with [this change](https://github.com/Patbox/sgui/commit/3a899c168add1790c885a5d83b0f6a9d54080143), though I'm not sure.

**Comment by Patbox** [comment]
1.16 version isn't really supported anymore, as I have only so much time (and supporting both is annoying because of java version change)
