### ISSUE TITLE
Gravity setting bug

### ISSUE THREAD

**Issue by Unleashed75** [Patbox/ArmorStandEditor#12]
In version 2.1.0 and still in 2.1.1
If an armor stand's "no gravity" setting it turned to "enabled" and then chunks it's in get unloaded, the next time "no gravity" is disabled, the armor stand will fall through any blocks below it and into the void.

**Comment by Unleashed75** [comment]
Just unloading the chucks and coming back does the same thing. Please fix this. I have friends who have lost gear now and I am going to remove this mod soon unless you start responding. If you can't fix it, then remove the gravity feature till someone can fix it

**Comment by Unleashed75** [comment]
oh wow, my comment sounded really rude and unrespectful. I'm sorry about that! Thank you for fixing the bug though, I hope it wasn't too much trouble. Keep up the great work

**Comment by Patbox** [comment]
It was caused by vanilla bug, but found way to fix that. It was simple fix
