### ISSUE TITLE
1.20.4 update?

### ISSUE THREAD

**Issue by witheredwojak** [Patbox/ArmorStandEditor#16]
It seems that this mod doesn't work on 1.20.4 Fabric 0.15.5 server. Log: https://paste.ee/p/lZk5R

**Comment by Patbox** [comment]
You likely use some mod that bundles old build of sgui, make sure all mods you use are 1.20.3/4 compatbile

**Comment by Patbox** [comment]
Thats not entire log

**Comment by witheredwojak** [comment]
> Thats not entire log

Okay, my bad. I thought you only needed the crash log. Here is a full (like, really full) log: https://paste.ee/p/ZoTf9

**Comment by Patbox** [comment]
You are using 2.1.2+1.20.1 version of armor stand editor instead of 1.20.3 one
