### ISSUE TITLE
Presets wipes current inventory of armor stand on apply.

### ISSUE THREAD

**Issue by KJP12** [Patbox/ArmorStandEditor#2]
## Expected Results
The armor stand to either retain the inventory, or if not possible, to dump the inventory into the player's or onto the ground.

## Steps to Reproduce
1. Place armor stand.
2. Give it armor and/or items. A textured player head was chosen.
3. Use flint on air, and select Presets, then, what I used, `Hello!`.
4. Apply to Armor Stand.
5. Note how the inventory is now gone.

## Environment
- Java 17.0.1
- Minecraft 1.18.1
- Fabric Loader 0.12.12 & Fabric Loom 0.10
- Creative Singleplayer
- GolfIV Client Development Environment
- ArmorStandEditor 1.13.1+1.18-rc3 (This appears to be the release JAR)
- headindex 1.0.4
- lazydfu 0.1.2
- Server Translations 1.4.2+1.17 (oops)

## Extras
There were no logs produced by this action, and as such, does not exist.

**Comment by Patbox** [comment]
It's intended behaviour, through I could make it toggable. Armor stands copy/paste stores items while on creative

**Comment by KJP12** [comment]
Oh, didn't know that. Might be appropriate to have a toggle, or at least document that this is a case, since I wasn't expecting the stand's inventory to be cleared on deploy. It's possible that other creative players wouldn't expect the same behaviour by default.

**Comment by Patbox** [comment]
Now it was split into it's own action
